apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-mysql
  template:
    metadata:
      labels:
        app: books-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: books-mysql-service
spec:
  selector:
    app: books-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
